env:
  browser: true
  es2021: true
  jquery: true
extends:
  - standard
  - plugin:import/recommended
  - plugin:promise/recommended
globals:
  miniShop2: true
  miniShop2Config: true
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  comma-dangle:
    - 2
    - always-multiline
ignorePatterns: [
  '**/mgr/**/*.js',
  '**/lib/**/*.js',
  '**/js/web/*.js',
]
