<?php

$xpdo_meta_map['msStorageOrder'] = [
    'package' => 'minishop2',
    'version' => '1.1',
    'table' => 'ms2_storage_orders',
    'extends' => 'xPDOSimpleObject',
    'tableMeta' => [
        'engine' => 'InnoDB',
    ],
    'fields' => [
        'user_id' => '',
        'receiver' => '',
        'phone' => '',
        'email' => '',
        'country' => '',
        'index' => '',
        'region' => '',
        'city' => '',
        'metro' => '',
        'street' => '',
        'building' => '',
        'entrance' => '',
        'floor' => '',
        'room' => '',
        'comment' => '',
        'text_address' => '',
        'properties' => null,
        'payment_id' => 0,
        'delivery_id' => 0,
        'createdon' => null,
        'updatedon' => null,
    ],
    'fieldMeta' => [
        'user_id' => [
            'dbtype' => 'varchar',
            'precision' => '50',
            'phptype' => 'string',
            'null' => false,
        ],
        'receiver' => [
            'dbtype' => 'varchar',
            'precision' => '191',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'phone' => [
            'dbtype' => 'varchar',
            'precision' => '20',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'email' => [
            'dbtype' => 'varchar',
            'precision' => '191',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'country' => [
            'dbtype' => 'varchar',
            'precision' => '100',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'index' => [
            'dbtype' => 'varchar',
            'precision' => '50',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'region' => [
            'dbtype' => 'varchar',
            'precision' => '100',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'city' => [
            'dbtype' => 'varchar',
            'precision' => '100',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'metro' => [
            'dbtype' => 'varchar',
            'precision' => '191',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'street' => [
            'dbtype' => 'varchar',
            'precision' => '191',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'building' => [
            'dbtype' => 'varchar',
            'precision' => '10',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'entrance' => [
            'dbtype' => 'varchar',
            'precision' => '10',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'floor' => [
            'dbtype' => 'varchar',
            'precision' => '10',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'room' => [
            'dbtype' => 'varchar',
            'precision' => '10',
            'phptype' => 'string',
            'null' => true,
            'default' => '',
        ],
        'comment' => [
            'dbtype' => 'text',
            'phptype' => 'json',
            'null' => true,
        ],
        'text_address' => [
            'dbtype' => 'text',
            'phptype' => 'json',
            'null' => true,
        ],
        'properties' => [
            'dbtype' => 'text',
            'phptype' => 'json',
            'null' => true,
        ],
        'payment_id' => [
            'dbtype' => 'int',
            'precision' => '10',
            'attributes' => 'unsigned',
            'phptype' => 'integer',
            'null' => false,
        ],
        'delivery_id' => [
            'dbtype' => 'int',
            'precision' => '10',
            'attributes' => 'unsigned',
            'phptype' => 'integer',
            'null' => false,
        ],
        'createdon' => [
            'dbtype' => 'datetime',
            'phptype' => 'datetime',
            'null' => true,
        ],
        'updatedon' => [
            'dbtype' => 'datetime',
            'phptype' => 'datetime',
            'null' => true,
        ],
    ],
    'indexes' => [
        'user_id' => [
            'alias' => 'user_id',
            'primary' => false,
            'unique' => false,
            'type' => 'BTREE',
            'columns' => [
                'user_id' => [
                    'length' => '',
                    'collation' => 'A',
                    'null' => false,
                ]
            ],
        ],
    ],
    'composites' => [],
    'aggregates' => [],
];
